frameworkVersion: ">=1.1.0 <2.0.0"

service: event-collector

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  apiKeys:
    - eventCollectorKeyDev


functions:
  postEvent: ${file(serverless/functions/postEvent.yaml)}


plugins:
  - serverless-python-requirements
  - serverless-aws-documentation

custom:
  pythonRequirements:
    dockerizePip: non-linux
    documentation: ${file(serverless/documentation/documentation.yaml)}