frameworkVersion: ">=1.1.0 <2.0.0"

service: event-collector

provider:
  name: aws
  apiKeys:
    - ${self:provider.stage}-eventCollectorApiKey
  apiGateway:
    apiKeySourceType: HEADER
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:putRecords
      Resource: 'arn:aws:kinesis:eu-west-1:***REMOVED***:stream/green.*.incoming.*'
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: 'arn:aws:lambda:eu-west-1:***REMOVED***:function:keycloak-authorizer-dev-authenticate'


functions:
  postEvent: ${file(serverless/functions/postEvent.yaml)}

package:
  exclude:
    - "**/*"
  include:
    - "src/main/*.py"
    - "serverless/documentation/schemas/*.json"

plugins:
  - serverless-python-requirements
  - serverless-aws-documentation

custom:
  pythonRequirements:
    dockerizePip: non-linux
  documentation: ${file(serverless/documentation/documentation.yaml)}