frameworkVersion: ">=1.64.0 <2.0.0"

service: event-collector

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  tracing:
    lambda: true
    apiGateway: true
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    METADATA_API: ${ssm:/dataplatform/shared/api-gateway-url}/metadata
    AUTHORIZER_API: ${ssm:/dataplatform/shared/api-gateway-url}/simple-dataset-authorizer
    ENABLE_AUTH: true
    KEYCLOAK_SERVER: ${ssm:/dataplatform/shared/keycloak-server-url}
    KEYCLOAK_REALM: api-catalog
    CLIENT_ID: event-collector
    CLIENT_SECRET: ${ssm:/dataplatform/${self:service.name}/keycloak-client-secret~true}
    SERVICE_NAME: ${self:service}
  rolePermissionsBoundary: "arn:aws:iam::#{AWS::AccountId}:policy/oslokommune/oslokommune-boundary"
  iamManagedPolicies:
    - 'arn:aws:iam::#{AWS::AccountId}:policy/event-collector-policy'
    - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'

functions:
  postEvents: ${file(serverless/functions/postEvents.yml)}
  postEvent: ${file(serverless/functions/postEvent.yml)}
  event_webhook: ${file(serverless/functions/post-event-webhook-auth.yml)}
  events_webhook: ${file(serverless/functions/post-events-webhook-auth.yml)}

package:
  exclude:
    - "**/*"
  include:
    - "event_collector/*.py"
    - "serverless/documentation/schemas/*.json"

plugins:
  - serverless-python-requirements
  - serverless-aws-documentation
  - serverless-plugin-git-variables
  - serverless-pseudo-parameters
  - serverless-es-logs

custom:
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: false
  esLogs:
    endpoint: ${ssm:/dataplatform/shared/elasticsearch-endpoint}
    index: dataplatform-services
    filterPattern: '{ $.function_name = "*" }'
  documentation: ${file(serverless/documentation/documentation.yml)}
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
  keycloakArn:
    prod: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:keycloak-authorizer-prod-authenticate
    dev: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:keycloak-authorizer-dev-authenticate
