frameworkVersion: ">=1.50.0 <2.0.0"

service: event-collector

provider:
  name: aws
  apiKeys:
    - ${self:provider.stage}-eventCollectorApiKey
  apiGateway:
    apiKeySourceType: HEADER
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  tracing:
    lambda: true
    apiGateway: true
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    METADATA_API: ${ssm:/dataplatform/metadata-api/url}
    AUTHORIZER_API: ${ssm:/dataplatform/simple-dataset-authorizer/url}
    ENABLE_AUTH: true
    KEYCLOAK_SERVER: ${ssm:/keycloak/client/server}
    KEYCLOAK_REALM: api-catalog
    CLIENT_ID: event-collector
    CLIENT_SECRET: ${ssm:/dataplatform/apis/event-collector/auth/client_secret~true}
  iamManagedPolicies:
    - Fn::Join:
        - ':'
        - - 'arn:aws:iam:'
          - Ref: AWS::AccountId
          - 'policy/event-collector-policy'
    - Fn::Join:
        - ':'
        - - 'arn:aws:iam::aws'
          - 'policy/AWSXRayDaemonWriteAccess'

functions:
  postEvents: ${file(serverless/functions/postEvents.yml)}
  postEvent: ${file(serverless/functions/postEvent.yml)}

package:
  exclude:
    - "**/*"
  include:
    - "src/main/*.py"
    - "serverless/documentation/schemas/*.json"

plugins:
  - serverless-python-requirements
  - serverless-aws-documentation
  - serverless-plugin-git-variables

custom:
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: false
  documentation: ${file(serverless/documentation/documentation.yml)}