frameworkVersion: ">=1.1.0 <2.0.0"

service: event-collector

provider:
  name: aws
  apiKeys:
    - ${self:provider.stage}-eventCollectorApiKey
  apiGateway:
    apiKeySourceType: HEADER
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  environment:
    METADATA_API_URL: ${ssm:/dataplatform/metadata-api/url}
  iamManagedPolicies:
    - Fn::Join:
        - ':'
        - - 'arn:aws:iam:'
          - Ref: AWS::AccountId
          - 'policy/event-collector-policy'


functions:
  postEvents: ${file(serverless/functions/postEvents.yml)}
  postEvent: ${file(serverless/functions/postEvent.yml)}

package:
  exclude:
    - "**/*"
  include:
    - "src/main/*.py"
    - "serverless/documentation/schemas/*.json"

plugins:
  - serverless-python-requirements
  - serverless-aws-documentation

custom:
  pythonRequirements:
    dockerizePip: non-linux
  documentation: ${file(serverless/documentation/documentation.yml)}