---
swagger: "2.0"
info:
  version: "2019-02-06T14:47:51Z"
  title: "dev-event-collector"
host: "nkf8mj7skg.execute-api.eu-west-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /event/{datasetId}/{version}:
    post:
      summary: "Takes a list of objects and puts them on a data stream."
      description: "Takes a list of objects and puts them on a data stream."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "version"
        in: "path"
        description: "Version for destination dataset"
        required: true
        type: "string"
      - name: "datasetId"
        in: "path"
        description: "Identifier for destination dataset"
        required: true
        type: "string"
      - in: "body"
        name: "postEventRequest"
        description: "Arbitrary json structure containing event data"
        required: true
        schema:
          $ref: "#/definitions/postEventRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/postEventStandardResponse"
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/postEventStandardResponse"
        500:
          description: "500 response"
          schema:
            $ref: "#/definitions/serverError"
        403:
          description: "403 response"
          schema:
            $ref: "#/definitions/postEventStandardResponse"
        404:
          description: "404 response"
          schema:
            $ref: "#/definitions/postEventStandardResponse"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  postEventRequest:
    title: "Post Event Request"
    type: "array"
    description: "An arbitrary json."
    items:
      type: "object"
      properties: {}
  postEventStandardResponse:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
    title: "Post Event Standard Response"
    description: "Response on success."
  serverError:
    type: "object"
    required:
    - "message"
    properties:
      failedElements:
        type: "array"
        items:
          type: "object"
          properties: {}
      message:
        type: "string"
    title: "Post Event Failed Elements Responses"
    description: "Internal server error."
